-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgmlanEjFHtZ+R+XXA
/MUAEB9e8CIHudZwtaXZiakZ+sqgCgYIKoZIzj0DAQehRANCAASspYtnrbudYaZe
YVePA+ppl78phcZw6eKXaDlKpe52rliiwJIvXF4zUkwHClg9ldQaL4bvKnUfCGRz
Es2MwOzw
-----END PRIVATE KEY-----